### ISSUE TITLE
Design the UI of the following pages

### ISSUE THREAD

**Issue by 0tuedon** [ease-it/ease-it-frontend#2]
The Reset page 2 and 3, the dashboard page, test page and test-page end 

Please make it reponsive

**Comment by Mo-wo** [comment]
Okay, noted

**Comment by 0tuedon** [comment]
@Mo-wo  What is the update please

**Comment by Mo-wo** [comment]
All pages done and responsive except dashboard page. Still working on the responsiveness.  It only looks good on laptop for now
