### ISSUE TITLE
Design the following page

### ISSUE THREAD

**Issue by 0tuedon** [ease-it/ease-it-frontend#4]
Well you are on the react track so you should know when to reuse a component

Design the News & Event page, Upload assignment 1 & 2 page, Attendance Page, Upload test 1 & 2 page 

Put your reusable components in the components folder. Datas in the utlis folder

**Comment by sivle19** [comment]
Just so i am absolutely sure, i will fork this repo and then clone it right?

**Comment by 0tuedon** [comment]
Done
